### ISSUE TITLE
Making this an ember addon

### ISSUE THREAD

**Issue by sivakumar-kailasam** [dstaley/ember-outdated#1]
Instead of having this globally installed, this could be made an ember-addon so that users can add this to devDependencies and run `ember outdated` instead. Here's the ember-cli docs reference for this - https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#includedcommands

**Comment by myared** [comment]
:+1:

**Comment by dstaley** [comment]
Totally open to this idea! My thinking was that installing it once and having it accessible to all your ember projects would be preferred over having to remember to add it to every project. However, if there's enough consensus over having this be a CLI addon, I'd be happy to rework it as such.

**Comment by dstaley** [comment]
What do y'all think about making two packages: `ember-outdated` (this package) which can be installed globally and provides the core functionality, and `ember-cli-outdated` which can be installed locally to an ember-cli project and lists `ember-outdated` as a dependency. This way, users like me who want to install a global package once can, and others who want to add it as a project dependency can do so as well. Also, since the `ember-outdated` package will continue to have the core functionality, they'll always be in sync.

**Comment by sivakumar-kailasam** [comment]
:+1:
